apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: east-west-gateway
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    hosts:
    - "*.local"
    tls:
      mode: AUTO_PASSTHROUGH
