apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
  cluster:
    name: {{clusterNamePrefix}}-cluster
    network: {{clusterNamePrefix}}-network
    multiCluster:
      enabled: true
  gateways:
    ingress:
      # does not work
      enabled: false
    egress:
      # does not work
      enabled: false
    openshiftRoute:
      enabled: false
  general:
    logging:
      componentLevels:
        default: info
  mode: ClusterWide
  meshConfig:
    discoverySelectors:
    - matchLabels:
        istio-injection: enabled
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  security:
    dataPlane:
      mtls: true
    identity:
      type: ThirdParty
    manageNetworkPolicy: false
  techPreview:
    global:
      meshID: bookinfo-mesh
  tracing:
    type: None
