apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor-15090
spec:
  selector:
    matchExpressions:
    - key: istio-prometheus-ignore
      operator: DoesNotExist
  targetLabels:
  - app
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 15s
    relabelings:
      - action: keep
        sourceLabels: [__meta_kubernetes_pod_container_name]
        regex: "istio-proxy"
      - action: keep
        sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
      - action: labeldrop
        regex: "__meta_kubernetes_pod_label_(.+)"
      - sourceLabels: [__meta_kubernetes_namespace]
        action: replace
        targetLabel: namespace
      - sourceLabels: [__meta_kubernetes_pod_name]
        action: replace
        targetLabel: pod_name
