apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system-1
spec:
  api:
    namespaces:
      exclude: []
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces:
    - bookinfo-1
    image_pull_policy: ''
    ingress:
      enabled: true
    namespace: istio-system-1
  external_services:
    custom_dashboards:
      namespace_label: kubernetes_namespace
    grafana:
      enabled: false
    istio:
      config_map_name: istio-basic
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-basic
      istiod_deployment_name: istiod-basic
      url_service_version: 'http://istiod-basic.istio-system-1:15014/version'
    prometheus:
      auth:
        token: secret:thanos-querier-web-token:token
        type: bearer
        use_kiali_token: false
      # This must be enabled. Otherwise, Kiali logs errors about Prometheus client configuration.
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: false
  installation_tag: 'Kiali [istio-system-1]'
  istio_namespace: istio-system-1
  version: v1.57
