apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
  gateways:
    ingress:
      routeConfig:
        enabled: false
    egress:
      enabled: false
    openshiftRoute:
      enabled: false
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  security:
    dataPlane:
      mtls: true
    manageNetworkPolicy: false
  # This is required to enable Prometheus metrics with Telemetry API
  techPreview:
    meshConfig:
      extensionProviders:
      - name: prometheus
        prometheus: {}
# These settings don't work. telemetry.v2.prometheus.enabled is set by spec.addons.prometheus.enabled
#  techPreview:
#    meshConfig:
#      enablePrometheusMerge: true
#    telemetry:
#      enabled: true
#      v2:
#        prometheus:
#          enabled: true
  tracing:
    type: None
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - bookinfo-1
