apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: true
      prometheus:
        auth:
          bearer:
            token: secret:thanos-querier-web-token:token
        thanosProxy:
          enabled: true
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    prometheus:
      enabled: false
  extensionProviders:
  - name: prometheus
    prometheus: {}
  gateways:
    ingress:
      routeConfig:
        enabled: false
    egress:
      enabled: false
    openshiftRoute:
      enabled: false
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  security:
    dataPlane:
      mtls: true
    manageNetworkPolicy: false
  tracing:
    type: None
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - bookinfo-1
