apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-to-use-prometheus-monitors
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "podmonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
