apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  profiles:
  - small
  security:
    certificateAuthority:
      cert-manager:
        address: cert-manager-istio-csr.cert-manager.svc:443
      type: cert-manager
    dataPlane:
      mtls: true
  tracing:
    type: None
  version: v2.3
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - bookinfo
