apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-to-use-prometheus-monitors
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "podmonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-to-use-prometheus-monitors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-to-use-prometheus-monitors
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{username}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-to-use-telemetry-api
rules:
- apiGroups: ["telemetry.istio.io"]
  resources: ["telemetries"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-to-use-telemetry-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-to-use-telemetry-api
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{username}}
