apiVersion: v1
kind: Service
metadata:
  name: ingress-gateway
spec:
  type: ClusterIP
  selector:
    gateway: httpbin
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-gateway
spec:
  selector:
    matchLabels:
      gateway: httpbin
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
      labels:
        gateway: httpbin
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: istio-proxy
          image: auto
